language: python
matrix:
  include:
    - python: 2.7
      stage: style
      name: "py2_pycodestyle"
      script: pycodestyle --max-line-length=100 config
    - python: 2.7
      stage: style
      name: "py2_pydocstyle"
      script: pydocstyle config
    - python: 2.7
      stage: style
      name: "py2_pylint"
      script: pylint config
    - python: 3.6
      stage: style
      name: "py3_pycodestyle"
      script: pycodestyle --max-line-length=100 config
    - python: 3.6
      stage: style
      name: "py3_pydocstyle"
      script: pydocstyle config
    - python: 3.6
      stage: style
      name: "py3_pylint"
      script: pylint config

    - python: 2.7
      stage: test
      script: pytest -vv --cov=config --cov-report=term-missing --cov-fail-under=45 tests
    - python: 3.6
      stage: test
      script: pytest -vv --cov=config --cov-report=term-missing --cov-fail-under=45 tests
git:
  depth: 3
install:
  - pip install --upgrade --upgrade-strategy eager pip setuptools wheel
  - pip install --upgrade --upgrade-strategy eager -e .[dev]
